_BASE_: [
  './yolov3_darknet53_270e_coco.yml',
]

bias: 1

epoch: 540

LearningRate:
  base_lr: 0.0005
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 432
    - 486
  - !LinearWarmup
    start_factor: 0.
    steps: 8000

TrainReader:
  batch_size: 4
  collate_batch: False

TrainDataset:
  !COCODataSet
    image_dir: train2017
    anno_path: annotations/instances_train2017.json
    dataset_dir: dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_score', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: dataset/coco



snapshot_epoch: 5
weights: output/yolov3_darknet53_advtrain/model_final
